name: Convert bloom
on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write
jobs:
  convert:
    strategy:
      matrix:
        model: [bigscience/bloom-560m, bigscience/bloom-1b1, bigscience/bloom-1b7, bigscience/bloom-3b]
    runs-on: ubuntu-latest
    steps:
      - name: Set up environment
        run: |
          echo "HUGGINGFACE_TOKEN=${{ secrets.HUGGINGFACE_TOKEN }}" >> $GITHUB_ENV

      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install torch
        run: pip install torch --index-url https://download.pytorch.org/whl/cpu

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Convert Model
        run: python convert.py bloom-ggml ./cache/ ${{ matrix.model }}   

  readme:
      needs: convert
      runs-on: ubuntu-latest
      steps:
      - name: Set up environment
        run: |
          echo "HUGGINGFACE_TOKEN=${{ secrets.HUGGINGFACE_TOKEN }}" >> $GITHUB_ENV

      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install README dependencies
        run: pip install -r readme_requirements.txt

      - name: Build Readme
        run: python generate_readme.py bloom-ggml


