name: Convert pythia
on:
  release:
    types: [published]
  workflow_dispatch:

env:
  REPO: pythia-ggml

permissions:
  contents: write
jobs:
  convert:
    strategy:
      matrix:
        model: [EleutherAI/pythia-70m, EleutherAI/pythia-160m, EleutherAI/pythia-410m,EleutherAI/pythia-1b,EleutherAI/pythia-1.4b,EleutherAI/pythia-2.8b]
    runs-on: ubuntu-latest
    steps:
      - name: Set up environment
        run: |
          echo "HUGGINGFACE_TOKEN=${{ secrets.HUGGINGFACE_TOKEN }}" >> $GITHUB_ENV

      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install torch
        run: pip install torch --index-url https://download.pytorch.org/whl/cpu

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Convert Model
        run: python convert.py $REPO ./cache/ ${{ matrix.model }}

  quantize:
    needs: convert
    strategy:
      matrix:
        model: [pythia-70m-f16.bin, pythia-160m-f16.bin, pythia-410m-f16.bin, pythia-1b-f16.bin, pythia-1.4b-f16.bin, pythia-2.8b-f16.bin]
    runs-on: ubuntu-latest
    steps:
      - name: Set up environment
        run: |
          echo "HUGGINGFACE_TOKEN=${{ secrets.HUGGINGFACE_TOKEN }}" >> $GITHUB_ENV

      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r quantize_requirements.txt

      - name: Convert Model
        run: python quantize.py $REPO ./cache/ ${{ matrix.model }}

  readme:
    needs: quantize
    runs-on: ubuntu-latest
    steps:
    - name: Set up environment
      run: |
        echo "HUGGINGFACE_TOKEN=${{ secrets.HUGGINGFACE_TOKEN }}" >> $GITHUB_ENV

    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install README dependencies
      run: pip install -r readme_requirements.txt

    - name: Build Readme
      run: python generate_readme.py $REPO
