name: Convert redpajama-3b
on:
  release:
    types: [published]
  workflow_dispatch:

env:
  REPO: redpajama-3b-ggml
  
permissions:
  contents: write
jobs:
  convert:
    strategy:
        matrix:
          model: [togethercomputer/RedPajama-INCITE-Chat-3B-v1, togethercomputer/RedPajama-INCITE-Instruct-3B-v1, togethercomputer/RedPajama-INCITE-Base-3B-v1]
    runs-on: ubuntu-latest
    steps:
      - name: Set up environment
        run: |
          echo "HUGGINGFACE_TOKEN=${{ secrets.HUGGINGFACE_TOKEN }}" >> $GITHUB_ENV

      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install torch
        run: pip install torch --index-url https://download.pytorch.org/whl/cpu

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Convert Model
        run: python convert.py $REPO ./cache/ ${{ matrix.model }}

  quantize:
    needs: convert
    strategy:
      matrix:
        model: [RedPajama-INCITE-Base-3B-v1-f16.bin, RedPajama-INCITE-Chat-3B-v1-f16.bin, RedPajama-INCITE-Instruct-3B-v1-f16.bin]
    runs-on: ubuntu-latest
    steps:
      - name: Set up environment
        run: |
          echo "HUGGINGFACE_TOKEN=${{ secrets.HUGGINGFACE_TOKEN }}" >> $GITHUB_ENV

      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r quantize_requirements.txt

      - name: Convert Model
        run: python quantize.py $REPO ./cache/ ${{ matrix.model }}

  readme:
    needs: quantize
    runs-on: ubuntu-latest
    steps:
    - name: Set up environment
      run: |
        echo "HUGGINGFACE_TOKEN=${{ secrets.HUGGINGFACE_TOKEN }}" >> $GITHUB_ENV

    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install README dependencies
      run: pip install -r readme_requirements.txt

    - name: Build Readme
      run: python generate_readme.py $REPO
